/**
 * Map of all exceptions from spdx and aboutcode.
 *
 * Last verified: 2026-09-01
 */

export const exceptions = new Map([
  [
    '389-exception',
    {
      license_key: '389-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'ada-linking-exception',
    {
      license_key: 'ada-linking-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'agpl-3.0-bacula',
    {
      license_key: 'agpl-3.0-bacula',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'agpl-3.0-linking-exception',
    {
      license_key: 'agpl-3.0-linking-exception',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'agpl-3.0-openssl',
    {
      license_key: 'agpl-3.0-openssl',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'agpl-generic-additional-terms',
    {
      license_key: 'agpl-generic-additional-terms',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'alfresco-exception-0.5',
    {
      license_key: 'alfresco-exception-0.5',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'apache-2.0-linking-exception',
    {
      license_key: 'apache-2.0-linking-exception',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'apache-2.0-runtime-library-exception',
    {
      license_key: 'apache-2.0-runtime-library-exception',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'apache-exception-llvm',
    {
      license_key: 'apache-exception-llvm',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'apache-patent-exception',
    {
      license_key: 'apache-patent-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'apache-patent-provision-exception',
    {
      license_key: 'apache-patent-provision-exception',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'apple-runtime-library-exception',
    {
      license_key: 'apple-runtime-library-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'apromore-exception-2.0',
    {
      license_key: 'apromore-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'aptana-exception-3.0',
    {
      license_key: 'aptana-exception-3.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'asn1cc-exception-gpl-2.0',
    {
      license_key: 'asn1cc-exception-gpl-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'asterisk-exception',
    {
      license_key: 'asterisk-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'asterisk-linking-protocols-exception',
    {
      license_key: 'asterisk-linking-protocols-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'autoconf-exception-2.0',
    {
      license_key: 'autoconf-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'autoconf-exception-3.0',
    {
      license_key: 'autoconf-exception-3.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'autoconf-macro-exception',
    {
      license_key: 'autoconf-macro-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'autoconf-simple-exception-2.0',
    {
      license_key: 'autoconf-simple-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'autoconf-simple-exception',
    {
      license_key: 'autoconf-simple-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'autoopts-exception-2.0',
    {
      license_key: 'autoopts-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'avisynth-c-interface-exception',
    {
      license_key: 'avisynth-c-interface-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'avisynth-linking-exception',
    {
      license_key: 'avisynth-linking-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'bacula-exception',
    {
      license_key: 'bacula-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'bash-exception-gpl',
    {
      license_key: 'bash-exception-gpl',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'bison-exception-2.0',
    {
      license_key: 'bison-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'bison-exception-2.2',
    {
      license_key: 'bison-exception-2.2',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'bootloader-exception',
    {
      license_key: 'bootloader-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'broadcom-linking-exception-2.0',
    {
      license_key: 'broadcom-linking-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'broadcom-linking-unmodified',
    {
      license_key: 'broadcom-linking-unmodified',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.3',
      deprecated_date: '2022-12-16',
    },
  ],
  [
    'broadcom-unmodified-exception',
    {
      license_key: 'broadcom-unmodified-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'bsd-new-far-manager',
    {
      license_key: 'bsd-new-far-manager',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'cgal-linking-exception',
    {
      license_key: 'cgal-linking-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'civicrm-exception-to-agpl-3.0',
    {
      license_key: 'civicrm-exception-to-agpl-3.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'classpath-exception-2.0',
    {
      license_key: 'classpath-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'clause-6-exception-lgpl-2.1',
    {
      license_key: 'clause-6-exception-lgpl-2.1',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'clisp-exception-2.0',
    {
      license_key: 'clisp-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'clojure-exception-to-gpl-3.0',
    {
      license_key: 'clojure-exception-to-gpl-3.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'cockroachdb-use-grant-for-bsl-1.1',
    {
      license_key: 'cockroachdb-use-grant-for-bsl-1.1',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'codelite-exception-to-gpl',
    {
      license_key: 'codelite-exception-to-gpl',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'commons-clause',
    {
      license_key: 'commons-clause',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'compuphase-linking-exception',
    {
      license_key: 'compuphase-linking-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'corporate-accountability-commercial-1.1',
    {
      license_key: 'corporate-accountability-commercial-1.1',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'cups-apple-os-exception',
    {
      license_key: 'cups-apple-os-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'cygwin-exception-2.0',
    {
      license_key: 'cygwin-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'cygwin-exception-3.0',
    {
      license_key: 'cygwin-exception-3.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'cygwin-exception-lgpl-3.0-plus',
    {
      license_key: 'cygwin-exception-lgpl-3.0-plus',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'dbmx-foss-exception-1.0.9',
    {
      license_key: 'dbmx-foss-exception-1.0.9',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'dbmx-linking-exception-1.0',
    {
      license_key: 'dbmx-linking-exception-1.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'dify-exception-apache-2.0',
    {
      license_key: 'dify-exception-apache-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'digia-qt-exception-lgpl-2.1',
    {
      license_key: 'digia-qt-exception-lgpl-2.1',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'digirule-foss-exception',
    {
      license_key: 'digirule-foss-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'drakvuf-exception-2.0',
    {
      license_key: 'drakvuf-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'dune-exception',
    {
      license_key: 'dune-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'ecma-no-patent',
    {
      license_key: 'ecma-no-patent',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'ecos-exception-2.0',
    {
      license_key: 'ecos-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'ecos',
    {
      license_key: 'ecos',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'ekiga-exception-2.0-plus',
    {
      license_key: 'ekiga-exception-2.0-plus',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'emq-use-grant-for-bsl-1.1',
    {
      license_key: 'emq-use-grant-for-bsl-1.1',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'erlang-otp-linking-exception',
    {
      license_key: 'erlang-otp-linking-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'errbot-exception',
    {
      license_key: 'errbot-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'far-manager-exception',
    {
      license_key: 'far-manager-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'fawkes-runtime-exception',
    {
      license_key: 'fawkes-runtime-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'fltk-exception-lgpl-2.0',
    {
      license_key: 'fltk-exception-lgpl-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'font-exception-gpl',
    {
      license_key: 'font-exception-gpl',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'freertos-exception-2.0',
    {
      license_key: 'freertos-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'fujion-exception-to-apache-2.0',
    {
      license_key: 'fujion-exception-to-apache-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'gcc-compiler-exception-2.0',
    {
      license_key: 'gcc-compiler-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'gcc-exception-2.0-note',
    {
      license_key: 'gcc-exception-2.0-note',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'gcc-exception-3.0',
    {
      license_key: 'gcc-exception-3.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'gcc-exception-3.1',
    {
      license_key: 'gcc-exception-3.1',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'gcc-linking-exception-2.0',
    {
      license_key: 'gcc-linking-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'generic-exception',
    {
      license_key: 'generic-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'genode-agpl-3.0-exception',
    {
      license_key: 'genode-agpl-3.0-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'geoserver-exception-2.0-plus',
    {
      license_key: 'geoserver-exception-2.0-plus',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'gigablast-apache-2.0-exception',
    {
      license_key: 'gigablast-apache-2.0-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'gmsh-exception',
    {
      license_key: 'gmsh-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'gnome-examples-exception',
    {
      license_key: 'gnome-examples-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'gnu-javamail-exception',
    {
      license_key: 'gnu-javamail-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'gpl-2.0-autoconf',
    {
      license_key: 'gpl-2.0-autoconf',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-autoopts',
    {
      license_key: 'gpl-2.0-autoopts',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-bison-2.2',
    {
      license_key: 'gpl-2.0-bison-2.2',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-bison',
    {
      license_key: 'gpl-2.0-bison',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-broadcom-linking',
    {
      license_key: 'gpl-2.0-broadcom-linking',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-classpath',
    {
      license_key: 'gpl-2.0-classpath',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-cygwin',
    {
      license_key: 'gpl-2.0-cygwin',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-font',
    {
      license_key: 'gpl-2.0-font',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-freertos',
    {
      license_key: 'gpl-2.0-freertos',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-gcc-compiler-exception',
    {
      license_key: 'gpl-2.0-gcc-compiler-exception',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-gcc',
    {
      license_key: 'gpl-2.0-gcc',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-glibc',
    {
      license_key: 'gpl-2.0-glibc',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-guile',
    {
      license_key: 'gpl-2.0-guile',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-ice',
    {
      license_key: 'gpl-2.0-ice',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-independent-module-linking',
    {
      license_key: 'gpl-2.0-independent-module-linking',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-iolib',
    {
      license_key: 'gpl-2.0-iolib',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-iso-cpp',
    {
      license_key: 'gpl-2.0-iso-cpp',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-javascript',
    {
      license_key: 'gpl-2.0-javascript',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-kernel',
    {
      license_key: 'gpl-2.0-kernel',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-libgit2',
    {
      license_key: 'gpl-2.0-libgit2',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-library',
    {
      license_key: 'gpl-2.0-library',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-libtool',
    {
      license_key: 'gpl-2.0-libtool',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-lmbench',
    {
      license_key: 'gpl-2.0-lmbench',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-mysql-connector-odbc',
    {
      license_key: 'gpl-2.0-mysql-connector-odbc',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-mysql-floss',
    {
      license_key: 'gpl-2.0-mysql-floss',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-openjdk',
    {
      license_key: 'gpl-2.0-openjdk',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-openssl',
    {
      license_key: 'gpl-2.0-openssl',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-oracle-mysql-foss',
    {
      license_key: 'gpl-2.0-oracle-mysql-foss',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-oracle-openjdk',
    {
      license_key: 'gpl-2.0-oracle-openjdk',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-plus-ada',
    {
      license_key: 'gpl-2.0-plus-ada',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-plus-ekiga',
    {
      license_key: 'gpl-2.0-plus-ekiga',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-plus-gcc',
    {
      license_key: 'gpl-2.0-plus-gcc',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-plus-geoserver',
    {
      license_key: 'gpl-2.0-plus-geoserver',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-plus-linking',
    {
      license_key: 'gpl-2.0-plus-linking',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-plus-nant',
    {
      license_key: 'gpl-2.0-plus-nant',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-plus-openmotif',
    {
      license_key: 'gpl-2.0-plus-openmotif',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-plus-openssl',
    {
      license_key: 'gpl-2.0-plus-openssl',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-plus-sane',
    {
      license_key: 'gpl-2.0-plus-sane',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-plus-subcommander',
    {
      license_key: 'gpl-2.0-plus-subcommander',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-plus-syntext',
    {
      license_key: 'gpl-2.0-plus-syntext',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-plus-upx',
    {
      license_key: 'gpl-2.0-plus-upx',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-proguard',
    {
      license_key: 'gpl-2.0-proguard',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-qt-qca',
    {
      license_key: 'gpl-2.0-qt-qca',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-redhat',
    {
      license_key: 'gpl-2.0-redhat',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-rrdtool-floss',
    {
      license_key: 'gpl-2.0-rrdtool-floss',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-2.0-uboot',
    {
      license_key: 'gpl-2.0-uboot',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-3.0-389-ds-base-exception',
    {
      license_key: 'gpl-3.0-389-ds-base-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'gpl-3.0-aptana',
    {
      license_key: 'gpl-3.0-aptana',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-3.0-autoconf',
    {
      license_key: 'gpl-3.0-autoconf',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-3.0-bison',
    {
      license_key: 'gpl-3.0-bison',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-3.0-cygwin',
    {
      license_key: 'gpl-3.0-cygwin',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-3.0-font',
    {
      license_key: 'gpl-3.0-font',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-3.0-gcc',
    {
      license_key: 'gpl-3.0-gcc',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-3.0-interface-exception',
    {
      license_key: 'gpl-3.0-interface-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'gpl-3.0-linking-exception',
    {
      license_key: 'gpl-3.0-linking-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'gpl-3.0-linking-source-exception',
    {
      license_key: 'gpl-3.0-linking-source-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'gpl-3.0-openbd',
    {
      license_key: 'gpl-3.0-openbd',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-3.0-plus-openssl',
    {
      license_key: 'gpl-3.0-plus-openssl',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'gpl-generic-additional-terms',
    {
      license_key: 'gpl-generic-additional-terms',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'gplcc-1.0',
    {
      license_key: 'gplcc-1.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'gstreamer-exception-2.0',
    {
      license_key: 'gstreamer-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'gstreamer-exception-2005',
    {
      license_key: 'gstreamer-exception-2005',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'gstreamer-exception-2008',
    {
      license_key: 'gstreamer-exception-2008',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'guile-exception-2.0',
    {
      license_key: 'guile-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'i2p-gpl-java-exception',
    {
      license_key: 'i2p-gpl-java-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'ice-exception-2.0',
    {
      license_key: 'ice-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'inbox-zero-exception-3.0',
    {
      license_key: 'inbox-zero-exception-3.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'independent-module-linking-exception',
    {
      license_key: 'independent-module-linking-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'inria-linking-exception',
    {
      license_key: 'inria-linking-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'iolib-exception-2.0',
    {
      license_key: 'iolib-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'javascript-exception-2.0',
    {
      license_key: 'javascript-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'katlang-patents-exception-mit',
    {
      license_key: 'katlang-patents-exception-mit',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'kfqf-accepted-gpl',
    {
      license_key: 'kfqf-accepted-gpl',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'kicad-libraries-exception',
    {
      license_key: 'kicad-libraries-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'kvirc-openssl-exception',
    {
      license_key: 'kvirc-openssl-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'lgpl-2.0-fltk',
    {
      license_key: 'lgpl-2.0-fltk',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'lgpl-2.0-plus-gcc',
    {
      license_key: 'lgpl-2.0-plus-gcc',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'lgpl-2.1-digia-qt',
    {
      license_key: 'lgpl-2.1-digia-qt',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'lgpl-2.1-nokia-qt-1.0',
    {
      license_key: 'lgpl-2.1-nokia-qt-1.0',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'lgpl-2.1-nokia-qt-1.1',
    {
      license_key: 'lgpl-2.1-nokia-qt-1.1',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'lgpl-2.1-nokia-qt',
    {
      license_key: 'lgpl-2.1-nokia-qt',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'lgpl-2.1-plus-linking',
    {
      license_key: 'lgpl-2.1-plus-linking',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'lgpl-2.1-plus-unlimited-linking',
    {
      license_key: 'lgpl-2.1-plus-unlimited-linking',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'lgpl-2.1-qt-company-2017',
    {
      license_key: 'lgpl-2.1-qt-company-2017',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'lgpl-2.1-qt-company',
    {
      license_key: 'lgpl-2.1-qt-company',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'lgpl-2.1-rxtx',
    {
      license_key: 'lgpl-2.1-rxtx',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'lgpl-2.1-spell-checker',
    {
      license_key: 'lgpl-2.1-spell-checker',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'lgpl-3-plus-linking',
    {
      license_key: 'lgpl-3-plus-linking',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'lgpl-3.0-cygwin',
    {
      license_key: 'lgpl-3.0-cygwin',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'lgpl-3.0-linking-exception',
    {
      license_key: 'lgpl-3.0-linking-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'lgpl-3.0-plus-openssl',
    {
      license_key: 'lgpl-3.0-plus-openssl',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'lgpl-3.0-zeromq',
    {
      license_key: 'lgpl-3.0-zeromq',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'liberation-font-exception',
    {
      license_key: 'liberation-font-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'libpri-openh323-exception',
    {
      license_key: 'libpri-openh323-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'libroxml-exception-lgpl-2.1',
    {
      license_key: 'libroxml-exception-lgpl-2.1',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'libticables2-exception-gpl-2.0',
    {
      license_key: 'libticables2-exception-gpl-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'libtool-exception-2.0',
    {
      license_key: 'libtool-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'libtool-exception-lgpl',
    {
      license_key: 'libtool-exception-lgpl',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'libtool-exception',
    {
      license_key: 'libtool-exception',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'libwebsockets-exception',
    {
      license_key: 'libwebsockets-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'lightbend-use-grant-bsl-1.1',
    {
      license_key: 'lightbend-use-grant-bsl-1.1',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'linking-exception-2.0-plus',
    {
      license_key: 'linking-exception-2.0-plus',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'linking-exception-2.1-plus',
    {
      license_key: 'linking-exception-2.1-plus',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'linking-exception-agpl-3.0',
    {
      license_key: 'linking-exception-agpl-3.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'linking-exception-lgpl-2.0-plus',
    {
      license_key: 'linking-exception-lgpl-2.0-plus',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'linking-exception-lgpl-3.0',
    {
      license_key: 'linking-exception-lgpl-3.0',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'linux-syscall-exception-gpl',
    {
      license_key: 'linux-syscall-exception-gpl',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'llgpl',
    {
      license_key: 'llgpl',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'llvm-exception',
    {
      license_key: 'llvm-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'lmbench-exception-2.0',
    {
      license_key: 'lmbench-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'lzma-cpl-exception',
    {
      license_key: 'lzma-cpl-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'lzma-sdk-2006-exception',
    {
      license_key: 'lzma-sdk-2006-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'magpie-exception-1.0',
    {
      license_key: 'magpie-exception-1.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'make-human-exception',
    {
      license_key: 'make-human-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'mif-exception',
    {
      license_key: 'mif-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'mini-xml-exception-lgpl-2.0',
    {
      license_key: 'mini-xml-exception-lgpl-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'mini-xml',
    {
      license_key: 'mini-xml',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'mldonkey-exception-gpl-2.0',
    {
      license_key: 'mldonkey-exception-gpl-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'musescore-exception-gpl-2.0',
    {
      license_key: 'musescore-exception-gpl-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'musl-exception',
    {
      license_key: 'musl-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'mysql-connector-odbc-exception-2.0',
    {
      license_key: 'mysql-connector-odbc-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'mysql-floss-exception-2.0',
    {
      license_key: 'mysql-floss-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'mysql-linking-exception-2018',
    {
      license_key: 'mysql-linking-exception-2018',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'nant-exception-2.0-plus',
    {
      license_key: 'nant-exception-2.0-plus',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'nicta-exception',
    {
      license_key: 'nicta-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'nokia-qt-exception-1.1',
    {
      license_key: 'nokia-qt-exception-1.1',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'npsl-exception-0.92',
    {
      license_key: 'npsl-exception-0.92',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'npsl-exception-0.93',
    {
      license_key: 'npsl-exception-0.93',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'npsl-exception-0.94',
    {
      license_key: 'npsl-exception-0.94',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'npsl-exception-0.95',
    {
      license_key: 'npsl-exception-0.95',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'object-form-exception-to-mit',
    {
      license_key: 'object-form-exception-to-mit',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'ocaml-lgpl-linking-exception',
    {
      license_key: 'ocaml-lgpl-linking-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'occt-exception-1.0',
    {
      license_key: 'occt-exception-1.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'odb-floss-exception-2.0',
    {
      license_key: 'odb-floss-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'openbd-exception-3.0',
    {
      license_key: 'openbd-exception-3.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'openjdk-assembly-exception-1.0',
    {
      license_key: 'openjdk-assembly-exception-1.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'openjdk-classpath-exception-2.0',
    {
      license_key: 'openjdk-classpath-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'openjdk-exception',
    {
      license_key: 'openjdk-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'openmotif-exception-2.0-plus',
    {
      license_key: 'openmotif-exception-2.0-plus',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'openmrs-exception-to-mpl-2.0',
    {
      license_key: 'openmrs-exception-to-mpl-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'opensc-openssl-openpace-exception-gpl',
    {
      license_key: 'opensc-openssl-openpace-exception-gpl',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'openssl-exception-agpl-3.0-monit',
    {
      license_key: 'openssl-exception-agpl-3.0-monit',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'openssl-exception-agpl-3.0-plus',
    {
      license_key: 'openssl-exception-agpl-3.0-plus',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'openssl-exception-agpl-3.0',
    {
      license_key: 'openssl-exception-agpl-3.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'openssl-exception-gpl-2.0-plus',
    {
      license_key: 'openssl-exception-gpl-2.0-plus',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'openssl-exception-gpl-2.0',
    {
      license_key: 'openssl-exception-gpl-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'openssl-exception-gpl-3.0-plus',
    {
      license_key: 'openssl-exception-gpl-3.0-plus',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'openssl-exception-lgpl-2.0-plus',
    {
      license_key: 'openssl-exception-lgpl-2.0-plus',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'openssl-exception-lgpl-3.0-plus',
    {
      license_key: 'openssl-exception-lgpl-3.0-plus',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'openssl-exception-lgpl',
    {
      license_key: 'openssl-exception-lgpl',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'openssl-exception-mongodb-sspl',
    {
      license_key: 'openssl-exception-mongodb-sspl',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'openssl-nokia-psk-contribution',
    {
      license_key: 'openssl-nokia-psk-contribution',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'openvpn-openssl-exception',
    {
      license_key: 'openvpn-openssl-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'oracle-mysql-foss-exception-2.0',
    {
      license_key: 'oracle-mysql-foss-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'oracle-openjdk-classpath-exception-2.0',
    {
      license_key: 'oracle-openjdk-classpath-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'pcre2-exception',
    {
      license_key: 'pcre2-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'photoprism-exception-3.0',
    {
      license_key: 'photoprism-exception-3.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'pretalx-exception-3.0',
    {
      license_key: 'pretalx-exception-3.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'pretix-exception-3.0',
    {
      license_key: 'pretix-exception-3.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'proguard-exception-2.0',
    {
      license_key: 'proguard-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'ps-or-pdf-font-exception-20170817',
    {
      license_key: 'ps-or-pdf-font-exception-20170817',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'qcad-exception-gpl',
    {
      license_key: 'qcad-exception-gpl',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'qskinny-exception-lgpl-2.1',
    {
      license_key: 'qskinny-exception-lgpl-2.1',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'qt-company-exception-2017-lgpl-2.1',
    {
      license_key: 'qt-company-exception-2017-lgpl-2.1',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.0',
      deprecated_date: '2022-09-08',
    },
  ],
  [
    'qt-company-exception-lgpl-2.1',
    {
      license_key: 'qt-company-exception-lgpl-2.1',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'qt-gpl-exception-1.0',
    {
      license_key: 'qt-gpl-exception-1.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'qt-kde-linking-exception',
    {
      license_key: 'qt-kde-linking-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'qt-lgpl-exception-1.1',
    {
      license_key: 'qt-lgpl-exception-1.1',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'qt-qca-exception-2.0',
    {
      license_key: 'qt-qca-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'qwt-exception-1.0',
    {
      license_key: 'qwt-exception-1.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'reactos-exception-gpl-2.0',
    {
      license_key: 'reactos-exception-gpl-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'rrdtool-floss-exception-2.0',
    {
      license_key: 'rrdtool-floss-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'rsync-linking-exception',
    {
      license_key: 'rsync-linking-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'rtems-exception-2.0',
    {
      license_key: 'rtems-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'rxtx-exception-lgpl-2.1',
    {
      license_key: 'rxtx-exception-lgpl-2.1',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'sane-exception-2.0-plus',
    {
      license_key: 'sane-exception-2.0-plus',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'sencha-app-floss-exception',
    {
      license_key: 'sencha-app-floss-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'sencha-dev-floss-exception',
    {
      license_key: 'sencha-dev-floss-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'shl-2.0',
    {
      license_key: 'shl-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'shl-2.1',
    {
      license_key: 'shl-2.1',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'signal-gpl-3.0-exception',
    {
      license_key: 'signal-gpl-3.0-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'simple-library-usage-exception',
    {
      license_key: 'simple-library-usage-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'snapeda-design-exception-1.0',
    {
      license_key: 'snapeda-design-exception-1.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'spell-checker-exception-lgpl-2.1-plus',
    {
      license_key: 'spell-checker-exception-lgpl-2.1-plus',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'sqlitestudio-openssl-exception',
    {
      license_key: 'sqlitestudio-openssl-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'strongswan-exception',
    {
      license_key: 'strongswan-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'stunnel-exception',
    {
      license_key: 'stunnel-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'subcommander-exception-2.0-plus',
    {
      license_key: 'subcommander-exception-2.0-plus',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'swi-exception',
    {
      license_key: 'swi-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'syntext-serna-exception-1.0',
    {
      license_key: 'syntext-serna-exception-1.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'tex-exception',
    {
      license_key: 'tex-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'trolltech-gpl-exception-1.0',
    {
      license_key: 'trolltech-gpl-exception-1.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'trolltech-gpl-exception-1.1',
    {
      license_key: 'trolltech-gpl-exception-1.1',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'trolltech-gpl-exception-1.2',
    {
      license_key: 'trolltech-gpl-exception-1.2',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'u-boot-exception-2.0',
    {
      license_key: 'u-boot-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'ubdl',
    {
      license_key: 'ubdl',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'universal-foss-exception-1.0',
    {
      license_key: 'universal-foss-exception-1.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'unlimited-binary-linking',
    {
      license_key: 'unlimited-binary-linking',
      is_deprecated: true,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: 'v31.2.3',
      deprecated_date: '2022-12-16',
    },
  ],
  [
    'unlimited-binary-use-exception',
    {
      license_key: 'unlimited-binary-use-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'unlimited-linking-exception-gpl',
    {
      license_key: 'unlimited-linking-exception-gpl',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'unlimited-linking-exception-lgpl',
    {
      license_key: 'unlimited-linking-exception-lgpl',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'upx-exception-2.0-plus',
    {
      license_key: 'upx-exception-2.0-plus',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'vcvrack-exception-to-gpl-3.0',
    {
      license_key: 'vcvrack-exception-to-gpl-3.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'viewflow-agpl-3.0-exception',
    {
      license_key: 'viewflow-agpl-3.0-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'vsftpd-openssl-exception',
    {
      license_key: 'vsftpd-openssl-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'vym-exception-2.0',
    {
      license_key: 'vym-exception-2.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'wxwindows-exception-3.1',
    {
      license_key: 'wxwindows-exception-3.1',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'xenomai-gpl-exception',
    {
      license_key: 'xenomai-gpl-exception',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'zeromq-exception-lgpl-3.0',
    {
      license_key: 'zeromq-exception-lgpl-3.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'zrythm-exception-agpl-3.0',
    {
      license_key: 'zrythm-exception-agpl-3.0',
      is_deprecated: false,
      is_exception: true,
      source: 'aboutCode',
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    '389-exception',
    {
      license_key: '389-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'Asterisk-exception',
    {
      license_key: 'Asterisk-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'Asterisk-linking-protocols-exception',
    {
      license_key: 'Asterisk-linking-protocols-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'Autoconf-exception-2.0',
    {
      license_key: 'Autoconf-exception-2.0',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'Autoconf-exception-3.0',
    {
      license_key: 'Autoconf-exception-3.0',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'Autoconf-exception-generic',
    {
      license_key: 'Autoconf-exception-generic',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'Autoconf-exception-generic-3.0',
    {
      license_key: 'Autoconf-exception-generic-3.0',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'Autoconf-exception-macro',
    {
      license_key: 'Autoconf-exception-macro',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'Bison-exception-1.24',
    {
      license_key: 'Bison-exception-1.24',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'Bison-exception-2.2',
    {
      license_key: 'Bison-exception-2.2',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'Bootloader-exception',
    {
      license_key: 'Bootloader-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'CGAL-linking-exception',
    {
      license_key: 'CGAL-linking-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'Classpath-exception-2.0',
    {
      license_key: 'Classpath-exception-2.0',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'Classpath-exception-2.0-short',
    {
      license_key: 'Classpath-exception-2.0-short',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'CLISP-exception-2.0',
    {
      license_key: 'CLISP-exception-2.0',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'cryptsetup-OpenSSL-exception',
    {
      license_key: 'cryptsetup-OpenSSL-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'Digia-Qt-LGPL-exception-1.1',
    {
      license_key: 'Digia-Qt-LGPL-exception-1.1',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'DigiRule-FOSS-exception',
    {
      license_key: 'DigiRule-FOSS-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'eCos-exception-2.0',
    {
      license_key: 'eCos-exception-2.0',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'erlang-otp-linking-exception',
    {
      license_key: 'erlang-otp-linking-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'Fawkes-Runtime-exception',
    {
      license_key: 'Fawkes-Runtime-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'FLTK-exception',
    {
      license_key: 'FLTK-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'fmt-exception',
    {
      license_key: 'fmt-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'Font-exception-2.0',
    {
      license_key: 'Font-exception-2.0',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'freertos-exception-2.0',
    {
      license_key: 'freertos-exception-2.0',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'GCC-exception-2.0',
    {
      license_key: 'GCC-exception-2.0',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'GCC-exception-2.0-note',
    {
      license_key: 'GCC-exception-2.0-note',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'GCC-exception-3.1',
    {
      license_key: 'GCC-exception-3.1',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'Gmsh-exception',
    {
      license_key: 'Gmsh-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'GNAT-exception',
    {
      license_key: 'GNAT-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'GNOME-examples-exception',
    {
      license_key: 'GNOME-examples-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'GNU-compiler-exception',
    {
      license_key: 'GNU-compiler-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'gnu-javamail-exception',
    {
      license_key: 'gnu-javamail-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'Google-Patent-WebM',
    {
      license_key: 'Google-Patent-WebM',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'GPL-3.0-389-ds-base-exception',
    {
      license_key: 'GPL-3.0-389-ds-base-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'GPL-3.0-interface-exception',
    {
      license_key: 'GPL-3.0-interface-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'GPL-3.0-linking-exception',
    {
      license_key: 'GPL-3.0-linking-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'GPL-3.0-linking-source-exception',
    {
      license_key: 'GPL-3.0-linking-source-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'GPL-CC-1.0',
    {
      license_key: 'GPL-CC-1.0',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'GStreamer-exception-2005',
    {
      license_key: 'GStreamer-exception-2005',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'GStreamer-exception-2008',
    {
      license_key: 'GStreamer-exception-2008',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'harbour-exception',
    {
      license_key: 'harbour-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'i2p-gpl-java-exception',
    {
      license_key: 'i2p-gpl-java-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'Independent-modules-exception',
    {
      license_key: 'Independent-modules-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'KiCad-libraries-exception',
    {
      license_key: 'KiCad-libraries-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'kvirc-openssl-exception',
    {
      license_key: 'kvirc-openssl-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'LGPL-3.0-linking-exception',
    {
      license_key: 'LGPL-3.0-linking-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'libpri-OpenH323-exception',
    {
      license_key: 'libpri-OpenH323-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'Libtool-exception',
    {
      license_key: 'Libtool-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'Linux-syscall-note',
    {
      license_key: 'Linux-syscall-note',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'LLGPL',
    {
      license_key: 'LLGPL',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'LLVM-exception',
    {
      license_key: 'LLVM-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'LZMA-exception',
    {
      license_key: 'LZMA-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'mif-exception',
    {
      license_key: 'mif-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'mxml-exception',
    {
      license_key: 'mxml-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'Nokia-Qt-exception-1.1',
    {
      license_key: 'Nokia-Qt-exception-1.1',
      is_deprecated: true,
      source: 'spdx',
      is_exception: true,
      deprecated_since: 'v3.1',
      deprecated_date: '2018-04-14',
    },
  ],
  [
    'OCaml-LGPL-linking-exception',
    {
      license_key: 'OCaml-LGPL-linking-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'OCCT-exception-1.0',
    {
      license_key: 'OCCT-exception-1.0',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'OpenJDK-assembly-exception-1.0',
    {
      license_key: 'OpenJDK-assembly-exception-1.0',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'openvpn-openssl-exception',
    {
      license_key: 'openvpn-openssl-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'PCRE2-exception',
    {
      license_key: 'PCRE2-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'polyparse-exception',
    {
      license_key: 'polyparse-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'PS-or-PDF-font-exception-20170817',
    {
      license_key: 'PS-or-PDF-font-exception-20170817',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'QPL-1.0-INRIA-2004-exception',
    {
      license_key: 'QPL-1.0-INRIA-2004-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'Qt-GPL-exception-1.0',
    {
      license_key: 'Qt-GPL-exception-1.0',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'Qt-LGPL-exception-1.1',
    {
      license_key: 'Qt-LGPL-exception-1.1',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'Qwt-exception-1.0',
    {
      license_key: 'Qwt-exception-1.0',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'romic-exception',
    {
      license_key: 'romic-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'RRDtool-FLOSS-exception-2.0',
    {
      license_key: 'RRDtool-FLOSS-exception-2.0',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'rsync-linking-exception',
    {
      license_key: 'rsync-linking-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'SANE-exception',
    {
      license_key: 'SANE-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'SHL-2.0',
    {
      license_key: 'SHL-2.0',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'SHL-2.1',
    {
      license_key: 'SHL-2.1',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'Simple-Library-Usage-exception',
    {
      license_key: 'Simple-Library-Usage-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'Spelling-Provider-LGPL-exception',
    {
      license_key: 'Spelling-Provider-LGPL-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'sqlitestudio-OpenSSL-exception',
    {
      license_key: 'sqlitestudio-OpenSSL-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'stunnel-exception',
    {
      license_key: 'stunnel-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'SWI-exception',
    {
      license_key: 'SWI-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'Swift-exception',
    {
      license_key: 'Swift-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'Texinfo-exception',
    {
      license_key: 'Texinfo-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'u-boot-exception-2.0',
    {
      license_key: 'u-boot-exception-2.0',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'UBDL-exception',
    {
      license_key: 'UBDL-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'Universal-FOSS-exception-1.0',
    {
      license_key: 'Universal-FOSS-exception-1.0',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'vsftpd-openssl-exception',
    {
      license_key: 'vsftpd-openssl-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'WxWindows-exception-3.1',
    {
      license_key: 'WxWindows-exception-3.1',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
  [
    'x11vnc-openssl-exception',
    {
      license_key: 'x11vnc-openssl-exception',
      is_deprecated: false,
      source: 'spdx',
      is_exception: true,
      deprecated_since: null,
      deprecated_date: null,
    },
  ],
])
